# Generated by Django 5.2.5 on 2025-08-19 02:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='수신 이메일')),
                ('name', models.CharField(max_length=50, verbose_name='담당자명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '이메일 수신자',
                'verbose_name_plural': '이메일 수신자들',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100, verbose_name='매장명')),
                ('owner_name', models.CharField(max_length=50, verbose_name='대표자명')),
                ('phone_number', models.CharField(max_length=20, verbose_name='연락처')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='이메일')),
                ('business_type', models.CharField(choices=[('restaurant', '음식점'), ('cafe', '카페'), ('bar', '주점'), ('bakery', '베이커리'), ('other', '기타')], max_length=20, verbose_name='업종')),
                ('business_type_other', models.CharField(blank=True, max_length=50, verbose_name='기타 업종')),
                ('store_size', models.CharField(choices=[('small', '소형 (10평 미만)'), ('medium', '중형 (10-30평)'), ('large', '대형 (30평 이상)')], max_length=20, verbose_name='매장 규모')),
                ('location_type', models.CharField(choices=[('main_street', '대로변'), ('side_street', '이면도로'), ('building', '건물 내부'), ('underground', '지하'), ('other', '기타')], max_length=20, verbose_name='상권 위치')),
                ('location_detail', models.CharField(blank=True, max_length=200, verbose_name='상세 위치')),
                ('naver_registered', models.BooleanField(default=False, verbose_name='네이버 플레이스 등록 여부')),
                ('naver_photos_quality', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='사진 매력도 (1-5점)')),
                ('naver_reservation', models.BooleanField(default=False, verbose_name='예약 기능 활용')),
                ('naver_news_update', models.CharField(choices=[('daily', '매일'), ('weekly', '주 1-2회'), ('monthly', '월 1-2회'), ('rarely', '거의 안함'), ('never', '전혀 안함')], max_length=20, verbose_name='소식 업데이트 주기')),
                ('naver_directions', models.BooleanField(default=False, verbose_name='찾아오는 길 상세 설명')),
                ('naver_marketing_msg', models.BooleanField(default=False, verbose_name='무료 마케팅 메시지 활용')),
                ('naver_keywords', models.BooleanField(default=False, verbose_name='대표 키워드 SEO 최적화')),
                ('naver_video_clip', models.BooleanField(default=False, verbose_name='클립 영상 활용')),
                ('naver_statistics', models.BooleanField(default=False, verbose_name='통계 확인 및 분석')),
                ('instagram_searchable', models.BooleanField(default=False, verbose_name='인스타 검색 시 노출')),
                ('instagram_video_count', models.IntegerField(default=0, verbose_name='등재된 영상 개수')),
                ('instagram_has_reviews', models.BooleanField(default=False, verbose_name='인스타 후기 존재')),
                ('blog_content_recent', models.BooleanField(default=False, verbose_name='최신 블로그 콘텐츠')),
                ('blog_detailed_info', models.BooleanField(default=False, verbose_name='상세 정보 포함')),
                ('google_registered', models.BooleanField(default=False, verbose_name='구글 비즈니스 등록')),
                ('google_info_accurate', models.BooleanField(default=False, verbose_name='구글 정보 정확도')),
                ('ad_naver_place', models.BooleanField(default=False, verbose_name='네이버 플레이스 상위노출 광고')),
                ('ad_naver_place_budget', models.CharField(blank=True, max_length=50, verbose_name='네이버 플레이스 광고 예산')),
                ('ad_naver_powerlink', models.BooleanField(default=False, verbose_name='네이버 파워링크 광고')),
                ('ad_naver_powerlink_budget', models.CharField(blank=True, max_length=50, verbose_name='파워링크 광고 예산')),
                ('ad_instagram_reels', models.BooleanField(default=False, verbose_name='인스타 릴스 스폰서 광고')),
                ('ad_instagram_budget', models.CharField(blank=True, max_length=50, verbose_name='인스타 광고 예산')),
                ('main_concerns', models.TextField(blank=True, verbose_name='주요 고민사항')),
                ('desired_improvements', models.TextField(blank=True, verbose_name='개선 희망사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '설문조사 응답',
                'verbose_name_plural': '설문조사 응답들',
                'ordering': ['-created_at'],
            },
        ),
    ]
