# Generated by Django 5.2.5 on 2025-08-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='location_type',
            field=models.CharField(choices=[('downtown', '번화가/역주변'), ('landmark', '랜드마크 주변'), ('apartment', '아파트 주거상권'), ('villa', '연립/빌라 주거상권'), ('university', '대학상권'), ('office', '오피스/업무지구'), ('traditional', '전통시장 주변'), ('other', '기타')], max_length=20, verbose_name='상권 위치'),
        ),
    ]
