# Generated by Django 5.2.5 on 2025-08-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyresponse_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='agency_satisfaction',
            field=models.CharField(blank=True, choices=[('very_satisfied', '매우 만족'), ('satisfied', '만족'), ('neutral', '보통'), ('dissatisfied', '불만족'), ('very_dissatisfied', '매우 불만족')], max_length=20, verbose_name='대행사 만족도'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='agency_service_detail',
            field=models.TextField(blank=True, verbose_name='이용한 서비스 내용'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='used_marketing_agency',
            field=models.BooleanField(default=False, verbose_name='온라인 마케팅 대행사 이용 경험'),
        ),
    ]
